### ISSUE TITLE
No Break_points_with_assemble.gff

### ISSUE THREAD

**Issue by lcscs12345** [DMnBI/iMGEins#2]
Hi,

Thank you for maintaining this repo. I didn't get the GFF file Break_points_with_assemble.gff from the test run. Is this because of the error?

`java -jar -Xmx16g iMGEins_ReleaseVer1.1.1.jar`
`-i sample_data/iMGEins_sample.sam`
`-o sample_data/sample_out`
`-p sample_data/default_param_for_sample.txt`

    Parameter loading end.
    Running time: 0.005 sec
    Sam loading end.
    Running time: 0.8 sec
    Generating filtered bam...
    Filtered bam generated.
    Running time: 0.892 sec
    Sorting filtered bam...
    Waiting for bam sorting..
    Filtered bam sorted.
    Running time: 0.898 sec
    Indexing filtered bam...
    Waiting for bam indexing..
    Filtered bam indexed.
    Running time: 0.902 sec

    chr11 - Break point candidate predict start.
        
       Break point candidate predict end.
       Running time: 0.914 sec
                # of putative break Points: 15

        Break point filtering(support read) end.
        Running time: 0.915 sec
                # of filtered break Points: 4
                # of rescuable Break Points: 11
    java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:542)
        at java.lang.Integer.parseInt(Integer.java:615)
        at iMGEins.OverlapFilter(iMGEins.java:1030)
        at iMGEins.main(iMGEins.java:2544)

`ls sample_data/sample_out/`

    both_unmap1.fq
    bp_list_filt_chr11.txt
    filtered.bam log_chr11.txt
    rescuable_bp_list_filt_chr11.txt  
    soft_maps_chr11.sam
    both_unmap2.fq
    bp_list.txt
    filtered.sam
    merged_all_reads.fq  
    single_unmap_pair_chr11.sam

**Comment by cphillips3** [comment]
I'm having the same issue. Did you happen to find a work-a-round at all?
