### ISSUE TITLE
Running Sample Data

### ISSUE THREAD

**Issue by sph17** [DMnBI/iMGEins#6]
While running sample data as described, I came across this: 
```
Parameter loading end.
Running time: 0.022 sec
Sam loading end.
Running time: 55.99 sec
Generating filtered bam...
Filtered bam generated.
Running time: 56.049 sec
Sorting filtered bam...
Waiting for bam sorting..
Filtered bam sorted.
Running time: 56.056 sec
Indexing filtered bam...
Waiting for bam indexing..
Filtered bam indexed.
Running time: 56.061 sec

chr11 - Break point candidate predict start.
        Break point candidate predict end.
        Running time: 56.081 sec
                # of putative break Points: 15

        Break point filtering(support read) end.
        Running time: 56.089 sec
                # of filtered break Points: 4
                # of rescuable Break Points: 11
java.lang.NumberFormatException: null
        at java.base/java.lang.Integer.parseInt(Integer.java:620)
        at java.base/java.lang.Integer.parseInt(Integer.java:776)
        at iMGEins.OverlapFilter(iMGEins.java:1030)
        at iMGEins.main(iMGEins.java:2544)
```

I was wondering if anyone else has bumped into this exception?

**Comment by th-koechling** [comment]
Hello, I have encountered the same problem. Did you find a solution?

**Comment by sbresnahan** [comment]
I have encountered the same output and error.

**Comment by muqingyan** [comment]
Hello, I have encountered the same error. Have tried to install bowtie2-2.1.0 (wget --no-check-certificate -O bowtie.zip https://sourceforge.net/projects/bowtie-bio/files/bowtie2/2.1.0/bowtie2-2.1.0-linux-x86_64.zip/download), but still didn't work.
get the below error:
biodocker@0960d18109c0:/local$ java -jar -Xmx16g iMGEins_ReleaseVer1.1.1.jar -i sample_data/iMGEins_sampl
e.sam -o sample_data/test_results -p sample_data/default_param_for_sample.txt
Parameter loading end.
Running time: 0.007 sec
Sam loading end.
Running time: 0.563 sec
Generating filtered bam...
Filtered bam generated.
Running time: 0.634 sec
Sorting filtered bam...
Waiting for bam sorting..
Filtered bam sorted.
Running time: 0.636 sec
Indexing filtered bam...
Waiting for bam indexing..
Filtered bam indexed.
Running time: 0.638 sec

chr11 - Break point candidate predict start.
        Break point candidate predict end.
        Running time: 0.647 sec
                # of putative break Points: 15

        Break point filtering(support read) end.
        Running time: 0.652 sec
                # of filtered break Points: 4
                # of rescuable Break Points: 11
java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:542)
        at java.lang.Integer.parseInt(Integer.java:615)
        at iMGEins.OverlapFilter(iMGEins.java:1030)
        at iMGEins.main(iMGEins.java:2544)

Total running time: 0.654 sec
